spring:
  datasource:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: pass

logging:
  level:
    org.yenanlai.world.archetype.domain: debug